In [1]:
!pip install numpy pandas

   ---------------------------------------- 0.0/11.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.6 MB 1.3 MB/s eta 0:00:10
   ---------------------------------------- 0.1/11.6 MB 1.6 MB/s eta 0:00:08
   - -------------------------------------- 0.4/11.6 MB 3.4 MB/s eta 0:00:04
   --- ------------------------------------ 0.9/11.6 MB 5.7 MB/s eta 0:00:02
   ---- ----------------------------------- 1.2/11.6 MB 5.8 MB/s eta 0:00:02
   ----- ---------------------------------- 1.6/11.6 MB 6.4 MB/s eta 0:00:02
   ------- -------------------------------- 2.0/11.6 MB 6.8 MB/s eta 0:00:02
   -------- ------------------------------- 2.6/11.6 MB 7.8 MB/s eta 0:00:02
   ----------- ---------------------------- 3.3/11.6 MB 8.9 MB/s eta 0:00:01
   ----------- ---------------------------- 3.3/11.6 MB 8.9 MB/s eta 0:00:01
   ----------- ---------------------------- 3.3/11.6 MB 8.9 MB/s eta 0:00:01
   ------------ --------------------------- 3.5/11.6 MB 6.9 MB/s eta 0:00:02
   ---

In [2]:
import numpy as np

In [6]:
A = [1,2,3,4,5]
A

[1, 2, 3, 4, 5]

In [4]:
B = np.array([1,2,3,4,5])
B

array([1, 2, 3, 4, 5])

In [11]:
import sys 

#size of array
size_array = sys.getsizeof(1) * len(A)
print('Size array A: ', size_array)

Size array A:  140


In [10]:
size_numpy = B.itemsize * B.size
print('Size numpy: ', size_numpy)

Size numpy:  20


In [14]:
A = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10]
])

A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [15]:
A.shape

(2, 5)

In [ ]:
# El comando flatten nos sirve para aplanar un vector/arreglo


A.flatten()

In [17]:
A.flatten().shape

(10,)

In [18]:
# Con reshape podemos transponer las dimensiones del vector

A.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [19]:
A.reshape(10,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [20]:
A.reshape(-1,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [21]:
A.reshape(5,-1,1)

array([[[ 1],
        [ 2]],

       [[ 3],
        [ 4]],

       [[ 5],
        [ 6]],

       [[ 7],
        [ 8]],

       [[ 9],
        [10]]])

In [24]:
A.reshape(10,-1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [25]:
A.reshape(-1,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [31]:
C = np.arange(0, 100)
C.shape


(100,)

In [34]:
C.reshape(4, 25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [33]:
C.reshape(4, -1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [35]:
zeros = np.zeros([10, 2])
zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [36]:
ones = np.ones([10, 2])
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [39]:
D = np.array([1,2,3])
D * 2

array([2, 4, 6])

In [42]:
np.sqrt(D)

array([1.        , 1.41421356, 1.73205081])

In [43]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [44]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [45]:
np.mean(A)

5.5

In [46]:
np.median(A)

5.5